# Site settings
title: Gabriel Robledo
description: 'Freelance CTO'
subdescription: Entrepreneur-minded computer science engineer helping companies develop products from scratch to reality. I build teams, select tools, manage roadmaps, design and build web and mobile applications.
url: 'http://gabriel.robledo.me'
baseurl: '/'
google_analytics: 'UA-92831542-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gabriel Robledo'
  email: gabriel@robledo.me
  twitter_username: grobledo
  github_username:  grobledo
  linkedin_username:  gabrielrobledo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
